version: '3.8'
services:
  currency-conversion-api-test:
    build:
      context: Dockerfile.test
    ports:
      - ${PORT}:${PORT}
    container_name: currency-conversion-api-backend-test
    restart: always
    volumes:
      - .:/usr/src/currency-conversion-api-backend
      - ./node_modules:/usr/src/currency-conversion-api-backend/node_modules
    working_dir: /usr/src/currency-conversion-api-backend
    depends_on:
      - currency-conversion-api-database-test
    command:
      - /bin/sh
      - -c
      - |
        yarn migration:run
        yarn test
    environment:
      NODE_ENV: test

  currency-conversion-api-database-test:
    image: postgres:14.5
    container_name: currency-conversion-api-database-test
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db:/var/lib/postgresql/data
    command: postgres -p ${DB_PORT}
