name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run Tests
        run: |-
          docker build . -f Dockerfile.test
          docker-compose -f docker-compose.test.yml --env-file .env.test run currency-conversion-api-backend-test
          docker-compose -f docker-compose.test.yml --env-file .env.test down

